apiVersion: v1
kind: Secret
metadata:
  name: blog-secrets
type: Opaque
stringData:
  DB_USERNAME_PROD: booksapi_owner
  DB_PASSWORD_PROD: NyXcE3RP2aSp
  RAILS_MASTER_KEY: 9f977d954bd2020cc16cc8e1fbdb7662
