apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: read-only
  policy.csv: |
    p, role:admin, applications, *, *, allow
    g, your-github-username, role:admin
